---
- name: install nginx
  apt: name=nginx state=latest update_cache=yes install_recommends=yes
  tags:
  - packages
  - install
  - nginx
- name: "Restart nginx"
  service: name=nginx state=restarted
  tags:
  - restart
  - nginx
